name: Node.js CI/CD

on:
  push:
    branches: [ "main" ]

permissions: 
  contents: write 

jobs:
  build:
    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [16.19]
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
      env:
        DB_PATH: mongodb+srv://matthewfallon33:G4nIrdNiauYTkujg@checkout-db.faxceg5.mongodb.net/?retryWrites=true&w=majority
    - run: ${{ secrets.PULL }}
    - run: echo "${{ secrets.ENV_FILE }}" > .env
    - run: npm ci
    - run: npm run test
    - run: pm2 restart backendserver