name: Node.js CI/CD

on:
  push:
    branches: [ "main" ]

permissions: 
  contents: write 

jobs:
  build:
    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [16.19]
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
      env: 
        DB_PATH: ${{ secrets.DB_PATH }}
    - run: ${{ secrets.PULL }}
    - run: npm ci

    # TESTS: Need to setup a Test DB these tests clear the DB so can't have them in for main DB
    # - run: echo "DB_PATH=${{ secrets.DB_PATH }}" >> .env
    # - run: echo "STRIPE_SECRET_KEY=${{ secrets.STRIPE_SECRET_KEY }}" >> .env
    # - run: echo "APP_SECRET_KEY=${{ secrets.APP_SECRET_KEY }}" >> .env
    # - run: echo "JWT_EXPIRATION=${{ secrets.JWT_EXPIRATION }}" >> .env
    # - run: npm run test

    - run: pm2 restart backendserver